# Generated by Django 5.2.9 on 2025-12-14 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_contactinquiry'),
    ]

    operations = [
    ]
